name: space_farm
description: "Steam"
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  clock: ^1.1.2
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  http: ^1.4.0
  path: ^1.9.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  window_manager: ^0.5.0

dev_dependencies:
  carapacik_lints: ^1.12.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: en
  class_name: GeneratedLocalizations
  arb_dir: lib/src/common/constant/localization/translations
  output_dir: lib/src/common/constant/localization/generated
